# Makefile for invoking KiBot documentation and fabrication generation.
# See the .kibot directory for more information.

# generate documentation for all boards
all:
	kibot -b ./kicad_6/panel_dims.kicad_pcb -c ./.kibot/doc_gen.kibot.yaml

# delete all documentation
clean:
	rm -r docs
